# Generated by Django 4.2.6 on 2023-10-26 11:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('friendly_name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=254)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='')),
                ('image14', models.ImageField(blank=True, null=True, upload_to='')),
                ('image15', models.ImageField(blank=True, null=True, upload_to='')),
                ('image16', models.ImageField(blank=True, null=True, upload_to='')),
                ('image17', models.ImageField(blank=True, null=True, upload_to='')),
                ('image18', models.ImageField(blank=True, null=True, upload_to='')),
                ('image19', models.ImageField(blank=True, null=True, upload_to='')),
                ('image20', models.ImageField(blank=True, null=True, upload_to='')),
                ('image21', models.ImageField(blank=True, null=True, upload_to='')),
                ('image22', models.ImageField(blank=True, null=True, upload_to='')),
                ('image23', models.ImageField(blank=True, null=True, upload_to='')),
                ('image24', models.ImageField(blank=True, null=True, upload_to='')),
                ('image25', models.ImageField(blank=True, null=True, upload_to='')),
                ('image26', models.ImageField(blank=True, null=True, upload_to='')),
                ('image27', models.ImageField(blank=True, null=True, upload_to='')),
                ('image28', models.ImageField(blank=True, null=True, upload_to='')),
                ('image29', models.ImageField(blank=True, null=True, upload_to='')),
                ('image30', models.ImageField(blank=True, null=True, upload_to='')),
                ('hide', models.BooleanField(default=False)),
                ('courtesy_of_gallery', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='oeuvre.category')),
            ],
        ),
    ]
