# Generated by Django 4.2.6 on 2023-10-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image21',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image22',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image23',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image24',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image25',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image26',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image27',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image28',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image29',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image30',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image9',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeuvre.work')),
            ],
        ),
    ]
