# Generated by Django 4.2.6 on 2023-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0003_alter_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
