# Generated by Django 4.2.6 on 2023-10-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0004_remove_work_url_work_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-order', '-date')},
        ),
    ]
