# Generated by Django 4.2.6 on 2023-10-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0005_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('order', '-date')},
        ),
    ]
