# Generated by Django 4.2.6 on 2023-11-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0008_alter_image_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
