# Generated by Django 4.2.6 on 2024-02-09 08:59

from django.db import migrations
import django_advance_thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvre', '0010_alter_work_options_remove_work_order_alter_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(null=True, upload_to='thumbnails/'),
        ),
    ]
