# Generated by Django 4.2.6 on 2023-11-30 12:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='urltext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
