# Generated by Django 4.2.6 on 2023-11-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
    ]
