# Generated by Django 4.2.6 on 2024-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_info_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(verbose_name='date, format dd-mm-yyyy'),
        ),
    ]
