# Generated by Django 4.2.6 on 2026-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_info_options_alter_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube or Vimeo video URL to embed a player.', max_length=700, null=True, verbose_name='Video URL (YouTube or Vimeo)'),
        ),
    ]
