# Generated by Django 4.2.6 on 2023-11-09 10:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(default='Item', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
